#include <iostream>
#include "Rachel.h"

LET_ME_TELL_YOU A_STORY
SO
	THIS_KID i WAS 10;
	DO_YOU_BUY i > 1 BRO WATCH_OUT
		I_HAVE_SOME_BAD_NEWS_FOR i;
	ANYWAY
	IF i IS 1 THEN
	WATCH_OUT
		THEYRE_LIKE "Now this prints!" MAN;
	ANYWAY
	BUT_ACTUALLY_THOUGH IF i ISNT 10 THEN
	WATCH_OUT
		THEYRE_LIKE "This won't print" MAN;
	ANYWAY
	BUT_ACTUALLY_THOUGH
	WATCH_OUT
		THEYRE_LIKE "And now this doesn't print" MAN;
	ANYWAY
	I_FEEL_LIKE THAT_KID zoab WAS 0 AND_MAYBE zoab < 10 AND_MAYBE zoab GREW_UP THEN
		THEYRE_LIKE zoab MAN;
THE_END