#include <iostream>
#include "Rachel.h"

LET_ME_TELL_YOU A_STORY
SO
	THIS_KID i WAS 10;
	IF i IS 1 THEN
	WATCH_OUT
		THEYRE_LIKE "This won't print" MAN;
	ANYWAY
	BUT_ACTUALLY_THOUGH IF i ISNT 10 THEN
	WATCH_OUT
		THEYRE_LIKE "This won't print either" MAN;
	ANYWAY
	BUT_ACTUALLY_THOUGH
	WATCH_OUT
		THEYRE_LIKE "This will print" MAN;
	ANYWAY
THE_END